export const productData = [
  {
    id: `a1`,
    type: `shoes`,
    brand: `Jinko`,
    name: `Jinko Solar 405 Watt Solar Panel, JKM405M-72HL-v`,
    gender: `Men`,
    color: [``],
    size: [0],
    sale: ``,
    price: 299.05,
    rating: 5.8,
    new: false,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/320w/products/726/445/SOLAR_SPM140P_F4__69602.1530080044.jpg?c=2`,
    ],
    description: `Our solar panel brands are ruggedly manufactured to withstand lightening strikes, high winds, and hail.  We choose only the highest quality, highest-efficiency panels that are guaranteed to produce electricity for 25 years (but will continue to produce indefinitely!). Our brands inlcude Ameresco Solar (formerly BP Solar), Canadian Solar, Solartech Power, Solarland, and more. You can buy solar panels from us by the pallet (which saves you money!) or if you need just a single panel, you can so that too.`,
    specification: [
      `144 5-busbar Diamond Mono PERC half-cells`,
      `PID Free and shade toleran`,
      `Certified for high snow (5400Pa) and wind (2400Pa) loads`,
      `IP67 Rated Junction Box for longevity in outdoor environments`,
      `High-voltage 1500V capability with UL & IEC certification`,
      `Run longer strings with lower balance of system costs and better LCOE.`,
    ],
  },
  {
    id: `a2`,
    type: `shoes`,
    brand: `Solarland`,
    name: `Solarland® 20 Watt, 12V High-Efficiency Standard Polycrystalline Solar Panel for Off-Grid Applications (SLP020-12U)`,
    gender: `Men`,
    color: [``],
    size: [0],
    sale: `Running`,
    price: 63.0,
    rating: 4.4,
    new: false,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/709/464/solarland_pvs__56251.1529913723.jpg?c=2`,
    ],
    description: `Our solar panel brands are ruggedly manufactured to withstand lightening strikes, high winds, and hail.  We choose only the highest quality, highest-efficiency panels that are guaranteed to produce electricity for 25 years (but will continue to produce indefinitely!). Our brands inlcude Ameresco Solar (formerly BP Solar), Canadian Solar, Solartech Power, Solarland, and more. You can buy solar panels from us by the pallet (which saves you money!) or if you need just a single panel, you can so that too.`,

    specification: [
      `Cells Polycrystalline silicon solar cell`,
      `No. of cells and connections 36(2X18)`,
      `Module dimension 576mm[22.68in.]x357mm[14.06in.]x30mm[1.18in.]`,
      `Weight 2.8kg[6.17lbs]`,
      `Packing information(Carton) 605mm[23.81in.]x215mm[8.46in.]x390mm[15.35in.]/(5pcs/ctn)`,
    ],
  },
  {
    id: `a3`,
    type: `shoes`,
    brand: `Ameresco`,
    name: `Ameresco Solar 10J 10 Watt, 12V Polycrystalline Solar Panel w/ IP65 Junction Box (AMS010J)`,
    gender: `Men`,
    color: [``],
    size: [0],
    sale: `Originals`,
    price: 92.0,
    rating: 4,
    new: true,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/320w/products/83/495/Ameresco_Solar_SX410M_10_Watt_PV_Module__61786.1410304650.jpg?c=2`,
    ],
    description: `Our solar panel brands are ruggedly manufactured to withstand lightening strikes, high winds, and hail.  We choose only the highest quality, highest-efficiency panels that are guaranteed to produce electricity for 25 years (but will continue to produce indefinitely!). Our brands inlcude Ameresco Solar (formerly BP Solar), Canadian Solar, Solartech Power, Solarland, and more. You can buy solar panels from us by the pallet (which saves you money!) or if you need just a single panel, you can so that too.`,
    specification: [
      `Maximum power (Pmax)`,
      `10W`,
      `7.2W`,
      `Voltage at Pmax (Vmpp)`,
      ` 17.9V`,
      `15.9V`,
      ` Current at Pmax (Impp)`,
      `0.56A`,
      `0.45A`,
      `Short circuit current (Isc)`,
      `0.58A`,
      ` 0.47A`,
      ` Open circuit voltage (Voc)`,
      ` 22.1V`,
      `  20.1V`,
    ],
  },
  {
    id: `a4`,
    type: `shoes`,
    brand: `Go Power`,
    name: `Go Power! 1500 Watt, 12V Pure Sine Wave Inverter w/ Two GFCI Equipped AC Outlets (GP-ISW1500-12)`,
    gender: `Men`,
    color: [``],
    size: [0],
    sale: `Originals`,
    price: 600.0,
    rating: 5,
    new: false,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/1086/1867/gp-isw1500-lg__06786.1551827535.jpg?c=2`,
    ],
    description: `BGreat for powering appliances, and electronics such as TVs, radios, laptop and computers, and security systems, the GP-ISW1500 1500-watt pure sine wave inverter is a strong performer for larger loads that demand a clean, pure source of AC power.

A sleek new design that is compact to fit in smaller spaces combines with a reduced weight make it an awesome solution for your off-road, expedition, or RV rig.`,
    specification: [
      `Continuous Output Power1500 W (VA)`,
      `Maximum Surge Rating2650 W (VA)`,
      `Output WaveformPure Sine Wave`,
      `Output Voltage Range ± 3%100 - 120 VAC (Dip Switch Selectable)`,
      `Input Voltage12 V: 10.5 - 16.5 VDC`,
      `Efficiency12 V: 91%`,
    ],
  },
  {
    id: `a5`,
    type: `shoes`,
    brand: `RMagnum Energy`,
    name: `RMagnum Energy MM612AE MM-AE Series 6000 Watt, 12VDC Modified Sine Wave Inverter/Charger`,
    gender: `Men`,
    color: [`Grey Two`],
    size: [0],
    sale: `Running`,
    price: 75.0,
    rating: 3.8,
    new: false,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/453/1136/Iron_Edison_magnum_mms1012g_1000_watt_12v_inverter_50_amp_pfc_charger_pure_sine_wave_energy__25809.1559875924.jpg?c=2`,
    ],
    description: `The MM612AE MM-AE Series 600 Watt, 12VDC modified sine wave inverter and battery charger from Magnum Energy is an excellent solution for low-power demand off-grid applications.All Magnum products are backordered, please contact for lead times or replacement options – sales@mrsolar.com / 888-680-2427`,
    specification: [
      `Standard transfer relay: Thestandard 20 amp transfer relaywill pass AC power throughthe inverter when using grid orgenerator power.V
      ersatile mounting: Mount theMM-AE Series on a shelf, wall,  oreven upside down.Fan cooled: The MM-AE Series isfan cooled, enabling the u
      nitto work well in confined spaces.If the inverter does exceedits temperature limits, it willautomatically shut down andthen restart when it cools down`,
    ],
  },
  {
    id: `a6`,
    type: `shoes`,
    brand: `Exeltech`,
    name: `Exeltech XP-125-48 XP Series 125 Watt, 48V True Sine Wave Inverter for Off-Grid and Mobile Applications`,
    gender: `Men`,
    color: [``],
    size: [0],
    sale: `Originals`,
    price: 165.0,
    rating: 1,
    new: true,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/441/1889/XP-125-true-sine-wave-inverter__87520.1560964628.jpg?c=2`,
    ],
    description: `The XP-125-48 inverter by Exeltech provides true sine wave DC-to-AC power and reliable performance for off-grid and mobile applications.`,
    specification: [
      `CONTINUOUS POWER 125W`,
      `SURGE POWER 150W`,
      `NO LOAD POWER 5W`,
      `OUTPUT VOLTAGE 100 +/-6%`,
      `OUTPUT CURRENT 1.2`,
      `WEIGHT LBS 2`,
    ],
  },

  {
    id: `a7`,
    type: `T-Shirts - Tops`,
    brand: `Discover`,
    name: `Discover® Battery 12V 215Ah Tubular Flooded Battery (3000TF-L)`,
    gender: `men`,
    color: [``],
    size: [""],
    price: 434.78,
    rating: 2.1,
    new: true,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/198/540/discover-batteries__49024.1410571321.jpg?c=2`,
    ],
    description: `
A wet or flooded cell battery operates by means of a liquid electrolyte solution (battery acid) covering all internal parts. Wet-cell batteries produce gas when overcharging. This gas must be able to escape which is why some refer to this type of battery as vented cell battery.`,
    specification: [`12V Tubular Flooded Battery`],
  },

  {
    id: `a8`,
    type: `Life Style`,
    brand: `UPG Universal`,
    name: `UPG Universal® 12V 250Ah Deep-Cycle Sealed AGM Solar Battery Non-Spillable (UB8D)`,
    gender: `Women`,
    color: [``],
    size: [""],
    sale: `Sustainable Fashion`,
    price: 631.0,
    rating: 3.7,
    new: true,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/196/538/upgi-universal-batteries__08342.1410571320.jpg?c=2`,
    ],
    description: ` AGM Batteries vs. Other Batteries
AGM Technology Explained. AGM batteries are based on the standard SLA (sealed lead-acid) battery construction. The difference lies in the addition of an ultra-thin glass mat (or AGM separator) that “absorbs” the electrolyte and makes the battery non-spillable. A sealed lead-acid battery is also known as a VRLA battery.`,
    specification: [`12V 250Ah AGM Battery`],
  },

  {
    id: `a9`,
    type: `shoes`,
    brand: `Concorde`,
    name: `Concorde Battery Sun XTender® 12V 84Ah Sealed Deep-Cycle VRLA/AGM Battery for Photovoltaic Systems (PVX840T)`,
    gender: `men`,
    color: [``],
    size: [0],
    sale: `Running`,
    price: 195.95,
    rating: 4.9,
    new: true,
    url: [
      `https://cdn11.bigcommerce.com/s-z25w13u/images/stencil/608x608/products/160/507/concorde-batteries__12056.1530113854.jpg?c=2`,
    ],
    description: `Calling all PR-chasers. Set a new personal best at your next marathon in the Deviate NITRO Elite racing shoes. Pinnacle responsiveness, propulsion, and cushioning in an extremely lightweight package (60g lighter than our previous Deviate model), this shoe exceeds the demands of runners chasing a best time in competitions. We’ve accomplished this through a thinner rubber, an even lighter nitrogen-injected NITRO Elite foam midsole, a leaner and stronger, thermo-formed carbon fibre plate, and a filmy upper that maximizes both breathability and lockdown. Now, take your mark.`,
    specification: [`Imported`],
  },
];
